/** Static exports of the same 3D artwork, generated by scripts/generate-promptbook-logo.ts. */
export const PROMPTBOOK_LOGO_ASSETS = {
    blue: {
        svg: '/logo/promptbook-logo-3d-blue.svg',
        png256: '/logo/promptbook-logo-3d-blue-256.png',
        png1024: '/logo/promptbook-logo-3d-blue-1024.png',
    },
    white: {
        svg: '/logo/promptbook-logo-3d-white.svg',
        png256: '/logo/promptbook-logo-3d-white-256.png',
        png1024: '/logo/promptbook-logo-3d-white-1024.png',
    },
} as const;

export type PromptbookLogoTone = keyof typeof PROMPTBOOK_LOGO_ASSETS;
