import { Building, Rocket, Shield } from 'lucide-react';

export const industryPricing = [
    {
        name: 'Standard',
        priceMonthly: '99',
        priceYearly: '999',
        currency: '$',
        period: 'per month',
        description: 'For a small or mid-sized industrial team.',
        icon: Building,
        iconName: 'Building',
        features: ['Up to 20 AI agents', 'Industry knowledge base', 'Priority support', 'Advanced analytics'],
        buttonText: 'Get Started',
        popular: false,
    },
    {
        name: 'Advanced',
        priceMonthly: '249',
        priceYearly: '2499',
        currency: '$',
        period: 'per month',
        description: 'For teams that need more agents, integrations, and support.',
        icon: Rocket,
        iconName: 'Rocket',
        features: [
            'Everything in Standard',
            'Up to 50 AI agents',
            'Custom integrations',
            'Dedicated account manager',
            '24/7 support',
        ],
        buttonText: 'Start Advanced Trial',
        popular: true,
    },
    {
        name: 'Enterprise',
        priceMonthly: 'Custom',
        priceYearly: 'Custom',
        currency: '',
        period: 'contact us',
        description: 'For large industrial deployments with custom requirements.',
        icon: Shield,
        iconName: 'Shield',
        features: [
            'Everything in Advanced',
            'Unlimited AI agents',
            'On-premises deployment',
            'Custom SLA',
            'Guided onboarding',
        ],
        buttonText: 'Contact Sales',
        popular: false,
    },
];
