/**
 * Rebuilds the transparent 3D logo exports with `npm run generate-logo`.
 *
 * The front outlines are measured from public/logo/promptbook-logo-blue-transparent-1024.png.
 * Its three disconnected pieces and the B counter are kept intact. Each face is extruded along its own
 * isometric normal; material gradients and a narrow rim supply the lighting. Blue and white use the same geometry.
 * Only this build-time script draws the artwork; pages and downloads share its static SVG and PNG files.
 */
import { writeFile } from 'node:fs/promises';
import path from 'node:path';
import sharp from 'sharp';
import { PROMPTBOOK_LOGO_ASSETS, type PromptbookLogoTone } from '../lib/branding/promptbookLogoAssets';

const VIEW_BOX_SIZE = 1024;
const DEPTH_STEPS = 36;
const OUTPUT_DIRECTORY = path.resolve(process.cwd(), 'public');

const LOGO_FACES = [
    {
        id: 'top',
        outline: 'M60 283 467 47V283Z',
        depth: [0, 32],
    },
    {
        id: 'p',
        outline:
            'M184 395C181 393 179 395 179 401V768C179 775 180 779 187 783L222 802' +
            'C224 803 226 803 226 800V638L274 666C311 688 335 672 346 642' +
            'C354 619 354 582 346 548C336 505 312 469 279 448Z',
        depth: [28, -16],
    },
    {
        id: 'b',
        outline:
            'M470 520 878 285V755L470 989Z' +
            'M588 498V878L661 836C723 801 760 746 760 675' +
            'C760 636 748 609 719 605C744 576 757 542 757 501' +
            'C757 456 741 421 705 438L592 492C589 494 588 495 588 498Z',
        depth: [-28, -16],
    },
] as const;

const MATERIALS = {
    blue: {
        top: ['#797bff', '#3434be', '#141077'],
        p: ['#494cdb', '#211a9d', '#090548'],
        b: ['#5b5bea', '#2420ac', '#09045b'],
        side: ['#343598', '#080431'],
        rim: ['#cedcff', '#777cea', '#272073'],
    },
    white: {
        top: ['#ffffff', '#edf6ff', '#b5cde4'],
        p: ['#f1f8ff', '#cfdfef', '#94acc9'],
        b: ['#ffffff', '#e2effa', '#b7cfe5'],
        side: ['#93aecb', '#4d6684'],
        rim: ['#ffffff', '#ffffff', '#a8c6df'],
    },
} as const;

function createGradient(id: string, colors: readonly string[]): string {
    const stops = colors.map((color, index) =>
        `<stop offset="${index / (colors.length - 1)}" stop-color="${color}"/>`,
    ).join('');

    return `<linearGradient id="${id}" x1="0" y1="0" x2="0.8" y2="1">${stops}</linearGradient>`;
}

function createFace({ id, depth }: (typeof LOGO_FACES)[number]): string {
    const layers = Array.from({ length: DEPTH_STEPS }, (_, index) => {
        const fraction = (DEPTH_STEPS - index) / DEPTH_STEPS;
        const horizontal = (depth[0] * fraction).toFixed(2);
        const vertical = (depth[1] * fraction).toFixed(2);

        return `<use href="#${id}" transform="translate(${horizontal} ${vertical})"/>`;
    }).join('');

    return `<g fill="url(#side)">${layers}</g>` +
        `<use href="#${id}" fill="url(#${id}-face)"/>` +
        `<use href="#${id}" fill="none" stroke="url(#rim)" stroke-width="3" stroke-linejoin="round"/>`;
}

function createLogoSvg(tone: PromptbookLogoTone): string {
    const material = MATERIALS[tone];
    const outlines = LOGO_FACES.map(({ id, outline }) => `<path id="${id}" d="${outline}"/>`).join('');
    const faceGradients = LOGO_FACES.map(({ id }) => createGradient(`${id}-face`, material[id])).join('');

    return '<?xml version="1.0" encoding="UTF-8"?>\n' +
        '<!-- Generated by npm run generate-logo. Edit scripts/generate-promptbook-logo.ts. -->\n' +
        `<svg xmlns="http://www.w3.org/2000/svg" width="${VIEW_BOX_SIZE}" height="${VIEW_BOX_SIZE}"` +
        ` viewBox="0 0 ${VIEW_BOX_SIZE} ${VIEW_BOX_SIZE}" fill-rule="evenodd">` +
        '<title>Promptbook 3D logo</title>' +
        `<defs>${outlines}${faceGradients}${createGradient('side', material.side)}` +
        `${createGradient('rim', material.rim)}</defs>${LOGO_FACES.map(createFace).join('')}</svg>\n`;
}

async function writeLogoAssets(tone: PromptbookLogoTone): Promise<void> {
    const assets = PROMPTBOOK_LOGO_ASSETS[tone];
    const svg = createLogoSvg(tone);

    await writeFile(path.join(OUTPUT_DIRECTORY, assets.svg), svg);
    for (const [size, destination] of [[256, assets.png256], [1024, assets.png1024]] as const) {
        await sharp(Buffer.from(svg), { density: 288 })
            .resize(size, size)
            .png()
            .toFile(path.join(OUTPUT_DIRECTORY, destination));
    }
}

async function main(): Promise<void> {
    await writeLogoAssets('blue');
    await writeLogoAssets('white');
    console.info('Generated blue and white 3D Promptbook logos (SVG, 256 PNG, 1024 PNG).');
}

main().catch((error: unknown) => {
    console.error(error);
    process.exitCode = 1;
});
